spring.application.name=smartbox-backend

server.port=8080

# Cấu hình kết nối PostgreSQL Supabase (Sử dụng Pooler tương thích IPv4 & Postgres ENUM)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require&stringtype=unspecified}
spring.datasource.username=${DB_USER:postgres.plcliseudrcublpuweng}
spring.datasource.password=${DB_PASSWORD:SmartBox@2026}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Cấu hình Swagger / OpenAPI
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==============================================================
# Cấu hình Spring Mail SMTP (Gửi Email Thật qua Gmail / SMTP)
# ==============================================================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=7000
spring.mail.properties.mail.smtp.timeout=7000
spring.mail.properties.mail.smtp.writetimeout=7000
smartbox.mail.sender-name=SmartBox IoT System


